[Service]
#ProtectHome=false
#ProtectSystem=false
#ReadWritePaths=/var/spool/cron/atjobs /var/spool/cron/atspool
#NoNewPrivileges=false

ProtectSystem=false
NoNewPrivileges=false
ProtectHome=false
PrivateDevices=false

ReadWritePaths=-/var/spool/atjobs
ReadWritePaths=-/var/spool/atspool
ReadWritePaths=-/var/spool/cron/atjobs
ReadWritePaths=-/var/spool/cron/atspool
ReadWritePaths=-/var/spool/at
ReadWritePaths=-/var/run/atd.pid
ReadWritePaths=-/run/atd.pid
