# 2026/05/25

[Service]

# ubuntu26.04,fedora44
#ProtectSystem=strict
ProtectSystem=false
#ProtectHome=true
ProtectHome=false

NoNewPrivileges=false
PrivateDevices=false

# dietpi mprotect() failed
MemoryDenyWriteExecute=false

ReadWritePaths=-/var/spool/atjobs
ReadWritePaths=-/var/spool/atspool
ReadWritePaths=-/var/spool/cron/atjobs
ReadWritePaths=-/var/spool/cron/atspool
ReadWritePaths=-/var/spool/at
ReadWritePaths=-/var/run/atd.pid
ReadWritePaths=-/run/atd.pid

#ReadWritePaths=-/var/www
